# Generated by Django 5.1.11 on 2025-09-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='item_definition',
            field=models.CharField(help_text='Item Definition', max_length=1500, verbose_name='Definition'),
        ),
    ]
