# Generated by Django 5.1.11 on 2025-09-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='position_number',
            field=models.CharField(blank=True, default='', help_text='Position Number', max_length=12, verbose_name='Position Number'),
        ),
    ]
