# Generated by Django 5.1.11 on 2025-09-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0002_alter_tariff_position_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='position_number',
            field=models.CharField(blank=True, help_text='Position Number', max_length=12, null=True, verbose_name='Position Number'),
        ),
    ]
